jobs: 
  include: 
    - language: node_js
      node_js:
        - "node"
        - "lts/*"
      before_install:
        - cd scraper
      install: 
        - npm ci
      script: 
        - npm test -- --runInBand

notifications: 
  email: tanet@trimas.no
